apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gamer-minerl-navdense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-model
  template:
    metadata:
      labels:
        app: ai-model
    spec:
      containers:
        - name: ai-model
          image: nerddotdad/ai-gamer:latest
          imagePullPolicy: Always # Ensure the latest image is pulled
          env:
            - name: INSTALL_PACKAGES
              value: "true"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: GITHUB_TOKEN
          volumeMounts:
            # Removed the mount for /app as it was overwriting the directory
            - name: model-volume
              mountPath: /data # You can use a different path for the volume if needed
      volumes:
        # Removed EmptyDir from /app to ensure the files inside the Docker image aren't overwritten
        - name: model-volume
          persistentVolumeClaim:
            claimName: model-pvc
